name: Build and tests

on: [ push, pull_request ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: test-data
          key: test-data


      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'gradle'
          check-latest: true

      - name: Setup Node 14 for JS tests
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: kotlin-js-store/yarn.lock

      - name: Setup Firefox and Xvfb for tests
        run: sudo apt-get update && sudo apt-get install firefox xvfb -y -f

      - name: Build with Gradle
        run: ./gradlew build -Pci -Pdisable-tests --console=plain

      - name: Run tests
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: xvfb-run --auto-servernum ./gradlew -Pci jvmTest jsLegacyTest jsIrTest -x inference:inference-ort-gpu:jvmTest --console=plain

      - name: Run heavy tests
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: xvfb-run --auto-servernum ./gradlew -Pci jvmHeavyTest jsLegacyHeavyTest jsIrHeavyTest -x inference:inference-ort-gpu:jvmHeavyTest --console=plain

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*
