name: Build and tests

on: [ push, pull_request ]

jobs:
  Build:
    runs-on: ubuntu-latest
    container: amazoncorretto:17

    steps:
      - uses: actions/checkout@v3

      - name: Build With Gradle
        run: ./gradlew assemble --parallel --console=plain --no-daemon

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*

  JVM-Test:
    runs-on: ubuntu-latest
    container: amazoncorretto:17

    steps:
      - uses: actions/checkout@v3

      - name: JVM Tests
        run: ./gradlew jvmTest --parallel --console=plain --no-daemon -Pci

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*

  JS-IR-Test:
    runs-on: ubuntu-latest
    container: registry.jetbrains.team/p/ki/containers-ci/ci-corretto-17-firefox:1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: JS IR Test
        run: xvfb-run --auto-servernum ./gradlew jsIrTest jsTest --parallel --console=plain --no-daemon -Pci

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*

  JS-Legacy-Test:
    runs-on: ubuntu-latest
    container: registry.jetbrains.team/p/ki/containers-ci/ci-corretto-17-firefox:1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: JS Legacy Test
        run: xvfb-run --auto-servernum ./gradlew jsLegacyTest --parallel --console=plain --no-daemon -Pci

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*

  JVM-Heavy-Test:
    runs-on: ubuntu-latest
    container: amazoncorretto:17

    steps:
      - uses: actions/checkout@v3

      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: test-data
          key: test-data-${{ hashFiles('buildSrc/src/main/**/DefaultS3Deps.kt') }}

      - name: JVM Heavy Test
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: ./gradlew jvmHeavyTest --console=plain -Pci --no-daemon

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*

  JS-IR-Heavy-Test:
    runs-on: ubuntu-latest
    container: registry.jetbrains.team/p/ki/containers-ci/ci-corretto-17-firefox:1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: test-data
          key: test-data-${{ hashFiles('buildSrc/src/main/**/DefaultS3Deps.kt') }}

      - name: JS IR Heavy Test
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: xvfb-run --auto-servernum ./gradlew jsIrHeavyTest -x :inference:inference-core:jsIrHeavyTest --console=plain -Pci --no-daemon

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*

  JS-Legacy-Heavy-Test:
    runs-on: ubuntu-latest
    container: registry.jetbrains.team/p/ki/containers-ci/ci-corretto-17-firefox:1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: test-data
          key: test-data-${{ hashFiles('buildSrc/src/main/**/DefaultS3Deps.kt') }}

      - name: JS Legacy Heavy Test
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: xvfb-run --auto-servernum ./gradlew jsLegacyHeavyTest -x :inference:inference-core:jsLegacyHeavyTest --console=plain -Pci --no-daemon

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*

  JS-IR-Heavy-Test-Inference-Core:
    runs-on: ubuntu-latest
    container: registry.jetbrains.team/p/ki/containers-ci/ci-corretto-17-firefox:1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: test-data
          key: test-data-${{ hashFiles('buildSrc/src/main/**/DefaultS3Deps.kt') }}

      - name: JS IR Heavy Test (Inference Core)
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: xvfb-run --auto-servernum ./gradlew :inference:inference-core:jsIrHeavyTest --console=plain -Pci --no-daemon

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*

  JS-Legacy-Heavy-Test-Inference-Core:
    runs-on: ubuntu-latest
    container: registry.jetbrains.team/p/ki/containers-ci/ci-corretto-17-firefox:1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: test-data
          key: test-data-${{ hashFiles('buildSrc/src/main/**/DefaultS3Deps.kt') }}

      - name: JS Legacy Heavy Test (Inference Core)
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: xvfb-run --auto-servernum ./gradlew :inference:inference-core:jsLegacyHeavyTest --console=plain -Pci --no-daemon

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            **/build/**/test-results/**/* |
            **/build/**/reports/**/*
